const User = require("../models/User");
const jwt = require("jsonwebtoken");
const axios = require("axios");

// =========================
// 🔹 SEND OTP
// =========================
exports.sendOTP = async (req, res) => {
  try {
    let { phone } = req.body;

    if (!phone) {
      return res.status(400).json({ message: "Phone number required" });
    }

    // Normalize phone number
    phone = phone.replace(/\D/g, "");

    const user = await User.findOne({ phone });
    if (!user) {
      return res.status(404).json({ message: "User not found. Contact Admin." });
    }

    // 🔹 Reset OTP count daily
    const today = new Date().toDateString();
    if (
      user.otpLastSentDate &&
      new Date(user.otpLastSentDate).toDateString() !== today
    ) {
      user.otpCount = 0;
    }

    // 🔹 Limit OTP to 3 per day
    if (user.otpCount >= 3) {
      return res.status(429).json({
        message: "OTP limit reached. Try again tomorrow.",
      });
    }

    // 🔥 SEND OTP via Message Central (V3 Verification)
    try {
      const customerId = process.env.MESSAGECENTRAL_CUSTOMER_ID.trim();
      const authToken = process.env.MESSAGECENTRAL_AUTH_TOKEN.trim();

      // We use the URL query parameters for V3 Verification
      const url = `https://cpaas.messagecentral.com/verification/v3/send?countryCode=91&customerId=${customerId}&flowType=SMS&mobileNumber=${phone}`;

      const response = await axios.post(url, {}, {
        headers: {
          "authToken": authToken,
          "Content-Type": "application/json"
        }
      });

      // Extract the OTP generated by Message Central (This ensures DLT compliance)
      const receivedOtp = response.data.data ? response.data.data.verificationCode : null;

      if (!receivedOtp) {
        throw new Error("Gateway accepted request but did not return a verification code.");
      }

      // ✅ Update user only if SMS gateway succeeded
      user.otp = receivedOtp.toString();
      user.otpExpiry = Date.now() + 5 * 60 * 1000; // 5 mins
      user.otpCount = (user.otpCount || 0) + 1;
      user.otpLastSentDate = new Date();
      await user.save();

      return res.json({
        message: `OTP Sent Successfully (${user.otpCount}/3)`,
        expiresIn: 300,
      });

    } catch (smsError) {
      console.error("SMS GATEWAY ERROR:", smsError.response?.data || smsError.message);
      return res.status(502).json({ 
        message: "SMS Gateway error. Please check credentials or DLT template.",
        error: smsError.response?.data 
      });
    }

  } catch (err) {
    console.error("Send OTP Error:", err.message);
    res.status(500).json({ message: "Server Error" });
  }
};

// =========================
// 🔹 VERIFY OTP
// =========================
exports.verifyOTP = async (req, res) => {
  try {
    let { phone, otp } = req.body;

    if (!phone || !otp) {
      return res.status(400).json({ message: "Phone and OTP required" });
    }

    phone = phone.replace(/\D/g, "");

    const user = await User.findOne({ phone });
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // 🔹 Validate OTP (Ensure string comparison)
    if (!user.otp || user.otp !== otp.toString() || user.otpExpiry < Date.now()) {
      return res.status(400).json({
        message: "Invalid or Expired OTP",
      });
    }

    // 🔹 Clear OTP
    user.otp = null;
    user.otpExpiry = null;
    await user.save();

    // 🔹 Generate JWT
    const token = jwt.sign(
      { id: user._id, role: "employee" },
      process.env.JWT_SECRET,
      { expiresIn: "8h" } // Extended to 8h for work shifts
    );

    res.json({
      message: "Login Successful",
      token,
      userId: user._id,
    });

  } catch (err) {
    console.error("Verify OTP Error:", err.message);
    res.status(500).json({ message: "Server Error" });
  }
};

// =========================
// 🔹 GET CURRENT USER
// =========================
exports.getMe = async (req, res) => {
  try {
    const user = await User.findById(req.user.id).select(
      "name phone hasSignedPolicy policyStatus"
    );
    res.json({ user });
  } catch (err) {
    res.status(500).json({ message: "Server Error" });
  }
};

// =========================
// 🔹 SUBMIT POLICY
// =========================
exports.submitPolicy = async (req, res) => {
  try {
    const { status } = req.body; 

    if (!["agreed", "disagreed"].includes(status)) {
      return res.status(400).json({ message: "Invalid status" });
    }

    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    user.policyStatus = status;
    user.hasSignedPolicy = true;
    await user.save();

    res.json({ message: "Policy response recorded successfully!" });
  } catch (err) {
    res.status(500).json({ message: "Server Error" });
  }
};